export { default as default } from './Instruction'
export { default as RInstruction } from './RInstruction'
export { default as IInstruction } from './IInstruction'
export { default as JInstruction } from './JInstruction'
export { default as utils } from './utils'